FROM electronuserland/builder:wine

ARG VERSION=0.0.0

COPY . /home
WORKDIR /home

RUN npm install --silent
RUN npm run build:linux -- -c.extraMetadata.version=${VERSION}
RUN npm run build:win -- -c.extraMetadata.version=${VERSION}

RUN ls -l build
