FROM maven:3-jdk-8-alpine

COPY code-generator /home
WORKDIR /home

RUN mvn -B clean
RUN mvn -B test

# To run locally:
# git clone https://github.com/cpswarm/ci.git
# cd ci
# git clone https://github.com/cpswarm/code-generator.git
# docker build -f Dockerfile-test .
