FROM maven:3-jdk-8

COPY . /home
WORKDIR /home

RUN mvn -B validate

# install xvfb to create a virtual display for tests
RUN apt update && apt install -y xvfb

RUN keytool -noprompt -importcert -trustcacerts \
    -file pert-demoenergy-virtus.ismb.polito.it.pem -alias pert-demoenergy-virtus.ismb.polito.it \
    -storepass changeit -keystore -J-Duser.language=en $JAVA_HOME/jre/lib/security/cacerts
    
# create a virtual display with Xvfb and set DISPLAY before starting mvn
RUN Xvfb :1 -screen 0 1024x768x16 & DISPLAY=:1.0 \
    mvn -B test -Dtest_server_ip=130.192.86.237 -Dtest_server_name=pert-demoenergy-virtus.ismb.polito.it -Dtest_server_username=orchestrator -Dtest_server_password=orchestrator  -Dtest_orchestrator_output_data_folder= -Dtest_manager_data_folder= -Doptimization_user=optimization_test -Dot_data_folder= -Dros_folder=   -Dtask_id=cpswarm_sar -Dparameters="" -Dgui=false -Dmonitoring=false -Ddimensions="Any" -Dmax_agents=3  -Dlocal_optimzation=false -Doptimization_configuration="{candidateCount:100, repeatCount:1, generationCount:100, simulationTimeoutSeconds:1200, seed:1234}"  -Djavax.xml.accessExternalDTD=all