FROM ubuntu:16.04

COPY . /home
WORKDIR /home/it.ismb.pert.cpswarm.simulation.gazebo

RUN apt update && apt install -yq bnd

RUN bnd package gazeboManager.bndrun


# Final artifact:
# /home/it.ismb.pert.cpswarm.simulation.gazebo/gazeboManager.jar
